name: AntiCombatLog
version: ${project.version}
main: net.badbird5907.anticombatlog.AntiCombatLog
api-version: 1.13
depend: [ Citizens ]
softdepend:
  - floodgate
  - WorldGuard
commands:
  anticombatlog:
    description: main command
    aliases: [combat,combatlog]
  resettag:
    description: reset combat tag
    aliases: [resetcombattag]
    permission: anticombatlog.command.resettag
permissions:
  anticombatlog.admin:
    description: nags about updates
    default: op